[project]
name = "241-hw6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.31.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "nbconvert>=7.16.6",
    "numpy>=2.0.2",
]
